Get users 21
JRSumner/backend-project pull request #5
Opened 2022-02-16 11:57 UTC by JRSumner

Completes both ticket #7 and #21.

2022-02-16 12:10 UTC, maddierosecodes requested changes
Just a couple of changes noted in the tests :)

2022-02-16 12:10 UTC, maddierosecodes commented on __tests__/app.test.js
> +        expect(body).toEqual({ inc_votes: 1 });
Please send back the entire article object rather than just the number of votes. The inc_votes key should be on the input object, and votes on the returning article object :)

2022-02-17 11:05 UTC, dav3rid commented on __tests__/app.test.js
> +        expect(body).toEqual({
I would still use `expect.objectContaining` here to account for additional properties in the future

2022-02-17 11:05 UTC, dav3rid commented on db/models/articles.model.js
>  const { fallback_application_name } = require("pg/lib/defaults");
Lines 1 & 2 here may have been auto imported by VS Code

2022-02-17 11:05 UTC, dav3rid commented on db/models/articles.model.js
> +      console.log(result);
Strip away console logs when you're done

2022-02-17 11:05 UTC, dav3rid commented on __tests__/app.test.js
> -        console.log("in test");
touché

2022-02-18 11:00 UTC, merged